const DEFAULT_FOCUS_TOTAL = 4;
const DEFAULT_FOCUS_TIME = 25;
const DEFAULT_BREAK_TIME = 5;
const DEFAULT_LONG_BREAK_TIME = 30;

export const DEFAULT_CONFIG = {
  focus: DEFAULT_FOCUS_TIME,
  break: DEFAULT_BREAK_TIME,
  longBreak: DEFAULT_LONG_BREAK_TIME,
  focusTotal: DEFAULT_FOCUS_TOTAL,
};

export const MAX_DURATION = 100;
export const MIN_DURATION = 5;
